### ISSUE TITLE
App was not running 

### ISSUE THREAD

**Issue by DevendarReddyDarukumalli** [honglvt/TalentRAT#2]
FAILURE: Build failed with an exception.
 
 Caused by: java.lang.IllegalStateException: SystemUtil.getIMEI(context) must not be null
        at com.hc.calling.socket.SocketConductor.connect2Server(SocketConductor.kt:37)
        at com.hc.calling.MainService.onCreate(MainService.kt:34)

**Comment by honglvt** [comment]
What's the model of your cellphone?
could you plz post the phone information in system settings

**Comment by honglvt** [comment]
hava u ever grant all permissions?

**Comment by DevendarReddyDarukumalli** [comment]
yes i granted all permissions after granting all the app is stopping 
 And my phone is Smartron SRT

**Comment by DevendarReddyDarukumalli** [comment]
Can you give the solution for it ???
